# generated by ingame editor v0.1


def load_state(game, scene):
    from pyvida import WalkArea, Rect
    scene.clean(["logo"])
    scene.walkarea.polygon([(1190, 423), (1584, 415), (1586, 682), (1239, 564)])
    scene.walkarea.waypoints([])
    # scene.music("data/music/armadillo_-_chipgurl.ogg")
    scene.scales["actors"] = 1.00
    logo = game.items["logo"]
    #logo.reclickable(Rect(0, 0, 400, 261))
    #logo.resolid(Rect(0, 0, 80, 50))
    logo.usage(True, True, True, True, True)
    logo.rescale(1.00)
    logo.reanchor((0, 0))
    logo.restand((150, 0))
    logo.relocate(scene, (100, 800))
