# generated by ingame editor v0.1


def load_state(game, scene):
    from pyvida import WalkArea, Rect
    scene.clean(["logo"])
    scene.walkareas.set([WalkArea().smart(game, [(100, 600), (900, 560), (920, 700), (80, 720)]),])
    # scene.music("data/music/armadillo_-_chipgurl.ogg")
    scene.scales["actors"] = 1.00
    logo = game.items["logo"]
    logo.reclickable(Rect(0, 0, 400, 261))
    logo.resolid(Rect(0, 0, 80, 50))
    logo.usage(True, True, True, True, True)
    logo.rescale(1.00)
    logo.reanchor((-200, -221))
    logo.restand((150, 0))
    logo.retalk((100, 221))
    logo.respeech((410, 261))
    logo.relocate(scene, (502, 192))
