# generated by ingame editor v0.2

def load_state(game, scene):
    from pyvida import WalkArea, Rect
    import os
    scene.clean(["pleasuretron", "logo","starfield", "queertech"])
    scene.walkareas.set([WalkArea().smart(game, [(100, 600), (900, 560), (920, 700), (80, 720)]),])
    scene.music("data/music/armadillo_-_chipgurl.ogg")
    pleasuretron = game.actors["pleasuretron"]
    pleasuretron.usage(True, True, False, False, False)
    pleasuretron.reclickable(Rect(0, 0, 486, 480))
    pleasuretron.resolid(Rect(0, 0, 80, 50))
    pleasuretron.rescale(1.00)
    pleasuretron.reanchor((-243, -408))
    pleasuretron.restand((193, 0))
    pleasuretron.retalk((121, 408))
    pleasuretron.respeech((496, 480))
    pleasuretron.relocate(scene, (1247, 521))
    pleasuretron.do("idle")
    scene.scales["actors"] = 1.00
    logo = game.items["logo"]
    logo.reclickable(Rect(0, 0, 400, 261))
    logo.resolid(Rect(0, 0, 80, 50))
    logo.usage(True, True, False, False, False)
    logo.rescale(1.00)
    logo.reanchor((-200, -221))
    logo.restand((150, 0))
    logo.retalk((100, 221))
    logo.respeech((410, 261))
    logo.relocate(scene, (502, 192))
    #starfield = game.actors["starfield"]
    #starfield.reanchor((0, 0))
    #starfield.reclickable(Rect(0, 0, 0, 0))
    queertech = game._items["queertech"]
    queertech.relocate(scene, (424, 469))
    queertech.reclickable(Rect(0, 0, 400, 261))
    queertech.resolid(Rect(0, 0, 80, 50))
    queertech.usage(True, True, False, False, False)
    queertech.rescale(1.25)
    queertech.reanchor((-350, 147))
    queertech.restand((150, 0))
    queertech.rename((0, 0))
    queertech.retext((410, 261))
    queertech.do("idle")

