#!/usr/bin/python3
#NOTE: Provided AS IS, no warranty for use!

#loopser - loops a series of images around onto a shorter set of images to create loopsing animations.
#cobbled together from websites and gpl stuff by Luke Miller 2015
#NOTE: Provided AS IS, no warranty for use!

from PIL import *
from PIL import Image
#import Image
import sys, os
from math import ceil
from optparse import OptionParser


def super_loopser():
    print("loopser v1.0 - by Luke Miller - 6/12/2015")
    usage = "usage: montager out_file file_list\nFor use with pyvida, loops a series of images around onto a shorter set of images to create looping animations. Use either -l OR -f (not both)";
    print("NOTE: Provided AS IS, no warranty for use!")
    parser = OptionParser()
#    parser.add_option("-", "--reverse", action="store_true", dest="reverse", help="Reverse file list", default=False)
#    parser.add_option("-f", "--flip", action="store_true", dest="flip", help="Flip the images left-right", default=False)
    parser.add_option("-l", "--loops", dest="loops", help="How many times to loops frames", default=-1, metavar="loops")
    parser.add_option("-f", "--frames", dest="frames", help="How many frames to use for loops", default=-1, metavar="loops")

    (options, args) = parser.parse_args()
    if len(args) < 2:
     	print(usage)
     	return
    ofname = args[0]
    if os.path.isfile(ofname):
        print("\n",ofname,"already exists.\n")
        print(usage)
        return
    files = args[1:]
    total_frames =len(files)
    loops = int(options.loops)
    frames = int(options.frames)
    if loops == -1 and frames == -1:
        print("No method for looping provided, use -l or -f.")
        print("Best results are when number of images %i is cleanly divisible by number of loops."%(total_frames))
        return

    if loops == -1:
        loops = total_frames/frames
    else:
        frames = total_frames/loops

    if total_frames // loops != total_frames / loops or float(loops) != int(loops):
        print("Best results are when number of images %i is cleanly divisible by number of loops %i."%(total_frames, loops))
        return
    print("Using %s original images, looping %s times, onto %s frames."%(total_frames, loops, frames))
    first_image = files[0]
    first_image = Image.open(first_image)
    print(first_image.size)
    new_frames = [Image.new('RGBA', first_image.size, (0,0,0,0)) for x in range(0, frames)]
#    for i in new_frames:
#        i.paste((50,80,100,255), (0,0, i.size[0], i.size[1]))

    for i, fname in enumerate(files):
        m = Image.open(fname).convert("RGBA") #get info from first image.
#        new_frames[0].paste(m, (0,0), m)
#        break
        frame_list = []
        for j in range(0, int(frames), int(frames/loops)):
            index = (i+j)%frames
            frame_list.append(index)
            new_frames[index].paste(m, (0,0), m)
#            new_frames[index] = Image.blend(new_frames[index], m, m)
        print("pasting image %s onto frames %s"%(fname, frame_list))

    name, ext = os.path.splitext(ofname)
    for i, im in enumerate(new_frames):
        im.save("%s%0.3d.png"%(name, i))

if __name__ == '__main__':
    super_loopser()
